Adds mapping remote field to Homer expected ones when loading message from URL
bastienwirtz/homer pull request #175
Opened 2021-01-04 11:49 UTC by luixal

## Description

A message can be loaded from an external URL that returns a json object with `title` and `content` fields. This PR adds the ability to map fields in case the data returned from the URL doesn't follow this naming.

More info about configuration and an example using a real URL added in the `configuration.md` and `tips-and-tricks.md` files.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I've read & comply with the [contributing guidelines](https://github.com/bastienwirtz/homer/blob/main/CONTRIBUTING.md)
- [x] I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers. 
- [x] I have made corresponding changes the documentation (README.md).
- [x] I've checked my modifications for any breaking changes, especially in the `config.yml` file

2021-01-07 20:25 UTC, luixal commented
Finally added the auto refresh based on `refreshInterval` field in configuration fields.

For keeping code simple, I refactored the `created` function of the `Message` component and split the logic for getting message loaded.

2021-01-13 19:16 UTC, bastienwirtz commented
Hi @luixal!

Thanks for your contribution! That sounds great, I will checkout and test that asap!

2021-02-18 05:59 UTC, bastienwirtz requested changes
Small details, looks great otherwise!
Thanks again!

2021-02-18 05:59 UTC, bastienwirtz commented on docs/tips-and-tricks.md
> +### Mapping Fields
Great doc ! Could you add a link in `docs/configuration.md` (l121) to this section?

2021-02-18 05:59 UTC, bastienwirtz commented on docs/tips-and-tricks.md
> +    mapping:
small indentation issue? `url` & `mapping` should be at the same level? (same on other exemples)

2021-02-18 05:59 UTC, bastienwirtz commented on docs/configuration.md
> +  # refreshInterval: 10000 # time interval to refresh message
```suggestion
  # refreshInterval: 10000 # Optionnal: time interval to refresh message
```

2021-02-23 19:20 UTC, luixal commented
Done! :)

2021-03-05 02:39 UTC, bastienwirtz approved these changes
:ok_hand: 

Thanks again @luixal !

2021-03-05 02:40 UTC, merged