cycle between automatic-light-dark themes
bastienwirtz/homer pull request #197
Opened 2021-03-06 14:16 UTC by GaaH

## Description

When clicking on the "toggle theme button", themes switch between auto-light-dark themes.

Fixes #183

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I've read & comply with the [contributing guidelines](https://github.com/bastienwirtz/homer/blob/main/CONTRIBUTING.md)
- [ ] I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers. 
- [ ] I have made corresponding changes the documentation (README.md).
- [x] I've checked my modifications for any breaking changes, especially in the `config.yml` file

2021-03-09 06:21 UTC, bastienwirtz requested changes
Hi @GaaH ! Thanks for your contribution! 
just reviewed & tested it, looks good to me. Just one thing could you add a title attribute (which should display a native popover on mouse hover) on the `<a>` with something like "auto switch" / "Dark" / "Light" to make it extra explicit (just in case some people are not familiar with the browsers / system preference) ? 
Thanks!

2021-03-09 06:27 UTC, bastienwirtz commented
Also If you could run  `yarn lint` to adjust the coding style, it would be perfect!

2021-03-09 17:38 UTC, GaaH commented
Everything should be nice and clean.

2021-03-10 05:33 UTC, bastienwirtz approved these changes
Perfect, thank you @GaaH !

2021-03-10 05:33 UTC, merged