Speedtesttracker integration
bastienwirtz/homer pull request #262
Opened 2021-08-26 18:40 UTC by boerniee

## Description

Added a service for the [SpeedtestTracker project](https://github.com/henrywhitaker3/Speedtest-Tracker). 

Fixes # (issue)

## Type of change

- [  ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [  ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] I've read & comply with the [contributing guidelines](https://github.com/bastienwirtz/homer/blob/main/CONTRIBUTING.md)
- [X] I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers. 
- [X] I have made corresponding changes the documentation (README.md).
- [X] I've checked my modifications for any breaking changes, especially in the `config.yml` file

2022-04-12 11:58 UTC, PedroC1999 commented
Hello!~

What additional work is required for this to be merged? interested in getting this closer to the PR being accepted :)

2022-04-20 19:51 UTC, Roundaround requested changes

2022-04-20 19:51 UTC, Roundaround commented on src/components/services/SpeedtestTracker.vue
> +<template>
Please extend the Generic service and modify only the #content / subtitle portion

2022-11-05 14:30 UTC, bastienwirtz commented
Hey there, 
Sorry for letting you wait so long ! I'm will merge this in a new branch to update it before merging it. 
Thank for your contribution !

2022-11-05 14:32 UTC, merged

2022-11-05 21:17 UTC, bastienwirtz commented
There you go: https://github.com/bastienwirtz/homer/blob/main/src/components/services/SpeedtestTracker.vue
This is merged on main :+1: