Adds indicator logo or icon on the right side.
bastienwirtz/homer pull request #539
Opened 2022-10-24 18:29 UTC by luixal

## Description

Adds yaml configuration options for showing logo (`indicator_logo`) or icon (`indicator_icon`) on the indicator slot (right side) of a service.

Fixes #336 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I've read & comply with the [contributing guidelines](https://github.com/bastienwirtz/homer/blob/main/CONTRIBUTING.md)
- [x] I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers. 
- [x] I have made corresponding changes to the documentation (README.md).
- [x] I've checked my modifications for any breaking changes, especially in the `config.yml` file

2022-10-27 20:24 UTC, bastienwirtz requested changes

2022-10-27 20:24 UTC, bastienwirtz commented on src/components/services/Generic.vue
> +              <slot name="indicator" class="indicator">
Double indicator slot ?

2022-10-31 13:17 UTC, luixal commented on src/components/services/Generic.vue
> +              <slot name="indicator" class="indicator">
My bad.

2022-11-04 19:36 UTC, luixal commented
Hi @bastienwirtz can you try to merge this PR (if you feel like that) now that I've reopenned it? I would like to make this changes as time is passing...

If it's better for you and github allows you to do show, just remove the closed PRs or the ones you can't merge and I'll make new ones.

2023-07-29 16:28 UTC, closed without merging