Ping service timeout
bastienwirtz/homer pull request #825
Opened 2024-11-13 14:13 UTC by Canti23

## Description

Added support for the timeout option for the Ping service. The default value is 2000 ms, which should be sufficient for most services.

Fixes #804

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I've read & comply with the [contributing guidelines](https://github.com/bastienwirtz/homer/blob/main/CONTRIBUTING.md)
- [x] I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers. 
- [x] I have made corresponding changes to the documentation (README.md).
- [x] I've checked my modifications for any breaking changes, especially in the `config.yml` file

2024-11-13 22:09 UTC, bastienwirtz requested changes
Small suggestion regarding the doc, aside from that, it's all good. Thanks @Canti23 !

2024-11-13 22:09 UTC, bastienwirtz commented on docs/customservices.md
> +  # timeout: 500
```suggestion
  # timeout: 500 # in ms. default 2000
```

2024-11-14 07:57 UTC, bastienwirtz approved these changes

2024-11-14 07:57 UTC, merged

2024-11-14 07:58 UTC, Canti23 commented
Thanks, thought about that, but haven't figured out how to write it succinctly :)